project:
  type: website
  output-dir: ../../docs

website:
  navbar:
    left:
      - text: "Home"
        href: title.qmd
      - text: "Introduction"
        href: introduction.qmd
      - text: "Data Description"
        href: data_description.qmd
      - text: "Data Analysis"
        href: data_analysis.qmd
      - text: "Discussion of Results"
        href: results_discussion.qmd
      - text: "Conclusion"
        href: conclusion.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true