---
title: Conclusions
output:
    pdf: 
        template: article-template.latex
---


Based on our analysis, it is clear there are key differences in the factors that drive GDP per capita across higher- and lower-performing regions. In higher-performing regions, employment and tax review demonstrated a strong, positve association on GDP per capita. Adjusted income growth, contrarily, had a negative impact on GDP per capita. All three indicators were statistically significant in predicting GDP per capita in this group, suggesting they collectively contribute to these North America's and Europe & Central Asia's economic standing. 

For lower-performing regions, tax revenue was the only indicator that was significant in predicting GDP growth, while adjusted income growth and employment ratio demonstrated weaker and statistically insignificant assionations. 

Our findings highlight the complexity of regional economic disparities and the variation in driving factors depending on the region of focus. For higher-performing regions, policies focused on employment rates and tax revenue may prove to be more effective, while lower-performing regions may see greater benefit by focusing their efforts on tax policy. Future research could explore additional factors that may be significant drivers in each of these regions to better improve our understanding of the key influences. Additional regions could also be included in future analysis, which may capture differences that we did observe in the highest and lowest-performing regions. 