---
title: Data Description
output:
    pdf: 
        template: article-template.latex
---


All data was obtained from the World Bank's [World Development Indicators](https://databank.worldbank.org/source/world-development-indicators/preview/on). This dataset is compiled from a list of officially recognized internation sources on a national, regional, and global scale, across time. 

To merge and clean the dataset, we utilized SQL and SQLAlchemy. From the main dataset, we wanted to create several dataframes. Some of the dataframes are region-based, where countries are grouped into seven geographical regions. Other dataframes are country-based data, where there is information about each individual country in the database. The timeframe used for each indicator is 2004-2023. 

Cleaning the data involved renaming column names to be more readable, replacing entries without values, and ordering the data by the name of the country/region. The cleaning procedure allowed for a more streamlined process for creating visualizations and regressions that informed our conclusions. More details about the data merging and cleaning process can be found in the scripts folder of this GitHub repository.

The specific variables we examined were as follows:

* GDP per capita (constant 2015 US$): Gross domestic product, the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products, divided by midyear population
* Adjusted net national income net national income per capita (annual % growth): gross national income minus consumption of fixed capital and natural resources depletion
* Employment to population ratio, 15+, total (%) (national estimate): Proportion of a country's population that is employed, where employment is defined as persons of working age who, during a short reference period, were engaged in any activity to produce goods or provide services for pay or profit 
* Tax revenue (% of GDP): total compulsory transfers to the central government for public purposes

We chose these indicators specifically as they provided the most comprehensive dataset, with limited missingness given the availability of observations from the World Bank.